sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install
  - npm i loader-utils
addons:
    code_climate:
        repo_token: 354a61ebebb73e09b1dbabff55de0a1350575913e0b3b20dfbb3426647addc96
