sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm install
addons:
    code_climate:
        repo_token: 354a61ebebb73e09b1dbabff55de0a1350575913e0b3b20dfbb3426647addc96
